### ISSUE TITLE
[1.16.3] Ticking (block) entity crash

### ISSUE THREAD

**Issue by bessiq** [binary404/MysticTools-2.0#1]
MC: 1.16.3
Forge: 34.1.0+ (last tested on 34.1.17)
mystictools-1.16.2-1.1.2.jar

Hi!

I know Mystic Tools isn't _technically_ supported on 1.16.3, but I thought I'd try it anyway, since a few other 1.16.2 mods I've tried have worked (and I also just really like this mod). My issue is this: a new singleplayer world will load to 100%, and sometimes I will even be able to enter the world for a few seconds or longer, but then the game crashes. The crash reports are either "Ticking entity" or "Ticking block entity" as seen below:

https://gist.github.com/bessiq/95ef4b1a1c308ec2c6a00a9410be984d

When I have time, I'll try to test on a separate instance with just Mystic Tools, and reply to this issue with the results. I just wanted to go ahead and post in case you noticed something in the logs. Thanks!

**Comment by binary404** [comment]
I am planning on updating to 1.16.3 soon. When I do I will take a look at that bug. I should have it done by next weekend.

**Comment by binary404** [comment]
I updated to 1.16.3 and the bug should be fixed. It looked like it was conflicting with the rare ice mod. I will do some testing before I release it to make sure.

**Comment by bessiq** [comment]
Awesome, sounds promising. fwiw, I did actually disable rare ice and tried again, but it also crashed. There is a 2nd crash report further down that same gist. And I haven't had time to disable more mods and test some more. Sorry!

**Comment by binary404** [comment]
What I changed should fix the second one as well.

**Comment by bessiq** [comment]
Cool, thanks for the quick fix. I love the RNG loots!

**Comment by binary404** [comment]
I haven't been able to get a crash with my testing so it should be all good. mystictools-1.16.3-1.1.4 should be uploaded to curseforge soon.

**Comment by binary404** [comment]
It has been approved. I you have any more issues feel free to post them here.
