### ISSUE TITLE
Suggestion: Jei Support / Wiki.

### ISSUE THREAD

**Issue by smallerYeet** [binary404/MysticTools-2.0#3]
Again Title is self-explanatory. 

Sometimes I just don't know what my effects are doing, possibly I figure it out but sadly not every time.
I also don't know what leveling my Tools (Modifiers) is doing exactly and I found no source to explain it.

**Comment by binary404** [comment]
I have been planning on making a wiki for quite some time I have just been busy working on some other mods.

**Comment by binary404** [comment]
Tool modifiers are consumed when you upgrade a tool in a tool upgrader.

**Comment by binary404** [comment]
What effects can you not figure out?

**Comment by smallerYeet** [comment]
How big the Growth Aura is. What the Tool Modifiers do

**Comment by smallerYeet** [comment]
Also, where can I find Mystic shards.

**Comment by binary404** [comment]
You can get shards when you drop a tool into a corrosion cauldron.

**Comment by binary404** [comment]
The wiki has been started. It will be a little while until I finish it but I don't see any reason to leave this open. So unless you have any more questions or concerns about the wiki I will close this issue.
