### ISSUE TITLE
Crash when firering a Quarz Arrorw from Archers Paradox

### ISSUE THREAD

**Issue by smallerYeet** [binary404/MysticTools-2.0#4]
Title say's it. Here is the [mod](https://www.curseforge.com/minecraft/mc-mods/archers-paradox)

Here is the log
[crash-2020-12-03_21.33.58-client.txt](https://github.com/binary404/MysticTools-2.0/files/5638796/crash-2020-12-03_21.33.58-client.txt)

**Comment by binary404** [comment]
I’ll take a look at. I should have it done by the weekend.

**Comment by binary404** [comment]
I think I fixed this, I'll release a new version once finish checking out the other bugs.

**Comment by binary404** [comment]
Should be fixed in 1.2.7
