### ISSUE TITLE
Crash when opening Loot case in SP

### ISSUE THREAD

**Issue by smallerYeet** [binary404/MysticTools-2.0#5]
Mc version : 1.16.3
Forge version: 34.1.42
Mod version: 1.2.6

Just what the Title says.
I can't open loot cases in Single player (not tried MP yet).
https://cdn.discordapp.com/attachments/738562486113927218/785612059131641856/crash-2020-12-07_21.59.25-server.txt

**Comment by binary404** [comment]
Try installing craft tweaker. You have gamestages running and my gamestages integration requires craft tweaker

**Comment by smallerYeet** [comment]
oh thanks!

**Comment by binary404** [comment]
If that fixed it then I don't believe there is any need to leave this open. Please confirm that adding craft tweaker fixed the crash.

**Comment by smallerYeet** [comment]
It fixed the crash
