### ISSUE TITLE
Lightning Rod is very loud and World wide.

### ISSUE THREAD

**Issue by smallerYeet** [binary404/MysticTools-2.0#6]
I play on my server and someone is using the Lightning Rod.
I can hear it at least 20k Blocks away.

Maybe it's the same for the Weapons, I can't confirm it tho

**Comment by binary404** [comment]
What lightning rod?

**Comment by binary404** [comment]
This mod does not have a lightning rod, only swords, pickaxes, axes, bows, and shovels.

**Comment by smallerYeet** [comment]
Yeah, i just realized. My friend told me the wrong mod. I am sorry

**Comment by binary404** [comment]
No problem
