### ISSUE TITLE
Suggsestion: Let player be able to check how many unique items they got / can get.

### ISSUE THREAD

**Issue by smallerYeet** [binary404/MysticTools-2.0#7]
Title is saying everything.

Would be nice to know how much unique you can get. Maybe after pulling one or via command / Item.

**Comment by binary404** [comment]
Sounds like a great idea

**Comment by binary404** [comment]
Any ideas for new unique effects?

**Comment by smallerYeet** [comment]
I will contact my Server (with about 10+ Player) what effects they would like to have!

**Comment by binary404** [comment]
Thank you so much. If any one has any suggestions whatsoever I would like to hear. I am completely open to new effects and features.

**Comment by binary404** [comment]
I made it so whenever you get a unique tool it will put a text message on the screen saying that you found a unique tool and how many left can be found. A command is coming soon.

**Comment by binary404** [comment]
Command is finished

**Comment by binary404** [comment]
Mystic tools 1.2.7 is now released. It fixes the archers paradox crash(I think) and it adds some details when getting unique tools.

**Comment by binary404** [comment]
If you have any ideas for unique effects just create a new post.
